# Generated by Django 3.2.7 on 2021-11-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paystubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paystub',
            old_name='A8090',
            new_name='Ser_no',
        ),
    ]
